<a href="https://colab.research.google.com/github/rahulkewat96742/Machine-Learning-with-Rahul-Kewat/blob/master/Linear%20Regression/3.%20(LR%20-%20Multivariate%20Regression)%20Salary%20on%20the%20basis%20of%20Interview%20Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import sklearn
import matplotlib.pyplot as plt
from word2number import w2n

In [0]:
csvdata = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv',names=['experience','testscore','interviewscore','salary'],skiprows=1)
csvdata.keys()

Index(['experience', 'testscore', 'interviewscore', 'salary'], dtype='object')

In [0]:
csvdata.experience = csvdata.experience.fillna('Zero')
csvdata.testscore = csvdata.testscore.fillna(csvdata.testscore.mean())

In [0]:
csvdata.experience = csvdata.experience.apply(w2n.word_to_num)

In [0]:
csvdata

experience  testscore  interviewscore  salary
0           0   8.000000               9   50000
1           0   8.000000               6   45000
2           5   6.000000               7   60000
3           2  10.000000              10   65000
4           7   9.000000               6   70000
5           3   7.000000              10   62000
6          10   7.857143               7   72000
7          11   7.000000               8   80000

In [0]:
X_train,X_test,y_train,y_test = sklearn.model_selection.train_test_split(csvdata.drop('salary', axis=1),csvdata['salary'],test_size=0.33)

In [0]:
regressor = linear_model.LinearRegression()

In [0]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
regressor.coef_

array([2369.32582895, 1846.48231983, 1709.42126514])

In [0]:
regressor.intercept_

25138.039887434206

In [0]:
regressor.predict(X_test)

array([50166.42603695, 55294.68983237, 65435.72739508])

In [0]:
print('Train Score : ',regressor.score(X_train,y_train))
print('Test Score : ',regressor.score(X_test,y_test))

Train Score :  0.9317652617964735
Test Score :  0.7465435840961718


In [0]:
regressor.predict([[2,9,6]])

array([56751.56001468])

In [0]:
regressor.predict([[12,10,10]])

array([89128.98568457])